version: '3'

services:
  pt:
    container_name: 'baseProject' # 在 docker 裡面的名字，沒有命名的話，會被 docker 自動取名
    build:
      context: ./
    # restart: always
    ports:
      - '8080:80' # 左邊是主機的端口，右邊是 container 對外的端口，因此對外的是左邊
    volumes:
      - ./:/app # 掛載，左邊為本機，右邊為 container 內部
    working_dir: /app
    deploy:
      mode: replicated
      replicas: 1
    # environment:
    #   ENV_TEST: ${ENV_TEST}
    command: sh entrypoint.sh # 這是為了要讓程式 hang 住
  # 用 docker ps 取得 container 的 name
  # 用 docker exec -it <container name> sh 進入 container ，來啟動 main.go 讓服務跑起來
  mongo:
    container_name: 'baseProject-mongo'
    image: 'mongo:4.2.16-bionic'
    ports:
      - '27000:27017' # 左邊對外的 port 號可以改
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
# 要連線到 mongo db ，去載 mongoDB compass 用 uri 的方式練線
# mongodb://admin:password@localhost:27017/
